blank_issues_enabled: false
contact_links:
  - name: Report a security vulnerability
    url: https://github.com/shashankh3/RadeonShift-AI/blob/master/.github/SECURITY.md
    about: Please report security vulnerabilities privately.
